# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
    sonata.admin.Countries:
        class: Apartment\ApartBundle\Admin\CountriesAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Content", label: "Countries" }
        arguments:
            - ~
            - Apartment\ApartBundle\Entity\Countries
            - ~
        calls:
            - [ setTranslationDomain, [ApartmentApartBundle]]
            
    sonata.admin.Towns:
        class: Apartment\ApartBundle\Admin\TownsAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Content", label: "Towns" }
        arguments:
            - ~
            - Apartment\ApartBundle\Entity\Towns
            - ~
        calls:
            - [ setTranslationDomain, [ApartmentApartBundle]]
            
    sonata.admin.Rooms:
        class: Apartment\ApartBundle\Admin\RoomsAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Content", label: "Rooms" }
        arguments:
            - ~
            - Apartment\ApartBundle\Entity\Rooms
            - ~
        calls:
            - [ setTranslationDomain, [ApartmentApartBundle]]